- name: Converge
  hosts: all
  roles:
    - role: role-partition
  vars:

    partition_disks:
      - name: /dev/vdb
        mkfs_opts: ""
        mount_opts: defaults
        path: /var/lib/backuppc
        owner: 110
        group: 115
        mode: 0750
